-- noqa: disable=all
-- This sql was autogenerated as a reference example using the library
-- CLI. Its format is tied to the specific database it was run against,
-- and it may not be correct for all databases. Use the CLI's build 
-- option to derive the best SQL for your dataset.

-- ###########################################################

CREATE EXTERNAL TABLE IF NOT EXISTS `umls`.`umls__semantic_types` (
    abbrev STRING,
    TUI STRING,
    full_type_name STRING
)
STORED AS PARQUET
LOCATION 's3://bucket/db_path/umls/SemanticTypes_2018AB'
tblproperties ("parquet.compression"="SNAPPY");

-- ###########################################################

CREATE EXTERNAL TABLE IF NOT EXISTS `umls`.`umls__semantic_groups` (
    abbrev STRING,
    group_name STRING,
    TUI STRING,
    full_type_name STRING
)
STORED AS PARQUET
LOCATION 's3://bucket/db_path/umls/SemGroups_2018'
tblproperties ("parquet.compression"="SNAPPY");

-- ###########################################################

CREATE EXTERNAL TABLE IF NOT EXISTS `umls`.`umls__rel_description` (
    REL STRING,
    REL_STR STRING
)
STORED AS PARQUET
LOCATION 's3://bucket/db_path/umls_rel'
tblproperties ("parquet.compression"="SNAPPY");

-- ###########################################################

CREATE EXTERNAL TABLE IF NOT EXISTS `umls`.`umls__rela_description` (
    RELA STRING,
    RELA_STR STRING
)
STORED AS PARQUET
LOCATION 's3://bucket/db_path/umls_rela'
tblproperties ("parquet.compression"="SNAPPY");

-- ###########################################################

CREATE EXTERNAL TABLE IF NOT EXISTS `umls`.`umls__tty_description` (
    TTY STRING,
    TTY_STR STRING
)
STORED AS PARQUET
LOCATION 's3://bucket/db_path/umls_tty'
tblproperties ("parquet.compression"="SNAPPY");

-- ###########################################################

CREATE EXTERNAL TABLE IF NOT EXISTS `umls`.`umls__tui_description` (
    STY STRING,
    TUI STRING,
    TUI_STR STRING
)
STORED AS PARQUET
LOCATION 's3://bucket/db_path/umls_tui'
tblproperties ("parquet.compression"="SNAPPY");
