name: PyPI

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build

    - name: Set version from tag
      run: |
        STUDY_VERSION=$(echo $GITHUB_REF_NAME | sed 's/^v//')
        sed -i "s/1\!0\.0\.0/$STUDY_VERSION/w changes.txt" cumulus_library_umls/__init__.py
        [ -s changes.txt ] || exit 1  # validate that we successfully set the version

    - name: Build
      run: python -m build

    - name: Publish
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
        print_hash: true
